### ISSUE TITLE
Apollo Federation Learning

### ISSUE THREAD

**Issue by omcneil** [openpracticelibrary/opl-content-api#7] opened 2020-05-11 19:08 UTC
As a dev, I need to understand Apollo Federation, so that I can implement new services for Open Practice Library.

**Comment by jameshbarton** [comment] 2020-05-11 19:58
Duplicate of https://github.com/openpracticelibrary/opl-api-gateway/issues/4

**Closed** 2020-05-11 19:58 UTC
Labels: delivery
